# Generated by Django 4.1 on 2022-11-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_ingreso',
            field=models.DateField(default='2022/11/16 19:22:29'),
        ),
    ]
